[package]
name = "ascii_graph"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.4.0"
libm = "0.2.6"
math = "0.10.0"
string = "0.3.0"
